# Store Slice as pickle

### Imports

In [8]:
from pathlib import Path


from python_utils.utils import save_object
from python_utils.utils import load_object

from python_utils.data_processing import parse_tecplot_slice_to_numpy_timeseries
from python_utils.data_processing import print_loaded_data_example

### General Args

In [ ]:
slice_folder_path = Path("../../../data/4pi_re1000_ha300.360_ch28.p1/SliceYZ_x0015/")
# slice_folder_path = Path("../../../data/4pi_re1000_ha1000.384.pi/SliceYZ_x0015/")
suffixes = [
    'fld',
    'gradF',
    'gradP',
    'gradU',
    'gradV',
    'gradW',
    ]
paths = [slice_folder_path / Path(f"sliceYZ_x0015_{suffix}.dat") for suffix in suffixes]

print_loaded_data_example_ = True
delete_files = False

### Load

In [ ]:
from pathlib import Path
import re
import numpy as np
from collections import defaultdict

def _extract_headers(line):
    """Extracts headers from a Tecplot variables line."""
    return [h.strip('"') for h in re.findall(r'"(.*?)"', line)]

def _parse_data_line(line, dtype):
    """Parses a single data line into a list of values."""
    return [dtype(v) for v in line.split()]

def _process_snapshot_data_with_fixed_coords(snapshot_data, headers, y_index, z_index, dtype, y_coords, z_coords, coord_to_index_map):
    """Processes the data of a single Tecplot snapshot using pre-defined coordinates."""
    num_y = len(y_coords)
    num_z = len(z_coords)
    num_vars = len(headers) - 2 if headers else 0
    snapshot_array = np.empty((num_y, num_z, num_vars), dtype=dtype)
    snapshot_array[:] = np.nan  # Initialize with NaN

    for row in snapshot_data:
        y_coord = row[y_index]
        z_coord = row[z_index]
        if (y_coord, z_coord) in coord_to_index_map:
            y_idx, z_idx = coord_to_index_map[(y_coord, z_coord)]
            data_values = np.array([row[i] for i in range(len(row)) if i not in [y_index, z_index]], dtype=dtype)
            snapshot_array[y_idx, z_idx, :] = data_values
        else:
            print(f"Warning: Coordinate (y={y_coord}, z={z_coord}) not found in the initial coordinate map.")
    return snapshot_array

def parse_tecplot_slice_to_numpy_4d_fixed_coords(
        file_path,
        *,
        dtype=float,
):
    """
    Parses a Tecplot slice file and returns a 4D NumPy array,
    where the dimensions represent:
    1. Time steps
    2. Y-coordinates (indexed)
    3. Z-coordinates (indexed)
    4. Variables

    Also returns a dictionary mapping (y_coord, z_coord) tuples to their
    corresponding index in the 4D array. This version assumes that the
    y and z coordinates and their corresponding indices remain the same
    across all snapshots, extracting them only from the first snapshot.
    """
    file_path = Path(file_path)

    # Precompile regex patterns
    re_title = re.compile(r'title')
    re_variables = re.compile(r'variables')
    re_zone = re.compile(r'zone')

    time_series_data = []
    headers = []
    found_headers = False
    y_index = -1
    z_index = -1
    initial_snapshot_data = []
    y_coords = []
    z_coords = []
    coord_to_index_map = {}
    first_snapshot_processed = False

    with file_path.open('r') as file:
        current_snapshot_data = []
        for line in file:
            line = line.strip()

            if not line:  # Skip empty lines
                continue

            if re_title.match(line):  # New snapshot starts here
                if current_snapshot_data and headers and y_index != -1 and z_index != -1:
                    if not first_snapshot_processed:
                        unique_y_set = set(row[y_index] for row in initial_snapshot_data)
                        unique_z_set = set(row[z_index] for row in initial_snapshot_data)
                        y_coords = sorted(list(unique_y_set))
                        z_coords = sorted(list(unique_z_set))
                        coord_to_index_map = {(y, z): (y_coords.index(y), z_coords.index(z)) for y in y_coords for z in z_coords}
                        first_snapshot_processed = True

                    if first_snapshot_processed:
                        snapshot_array = _process_snapshot_data_with_fixed_coords(
                            current_snapshot_data, headers, y_index, z_index, dtype, y_coords, z_coords, coord_to_index_map
                        )
                        time_series_data.append(snapshot_array)

                current_snapshot_data = []  # Reset for next snapshot

            elif re_variables.match(line):  # Extract headers only once
                if not found_headers:
                    found_headers = True
                    headers = _extract_headers(line)
                    try:
                        y_index = headers.index("y")
                        z_index = headers.index("z")
                    except ValueError:
                        print("Warning: 'y' and 'z' variables not found in headers.")
                        y_index = -1
                        z_index = -1

            elif not re_zone.match(line):  # Process data lines
                try:
                    values = _parse_data_line(line, dtype)
                    current_snapshot_data.append(values)
                    if not first_snapshot_processed and found_headers:
                        initial_snapshot_data.append(values)
                except ValueError:
                    print(f"Warning: Could not convert line to float values: {line}")

        # Process the last snapshot
        if current_snapshot_data and headers and y_index != -1 and z_index != -1:
            if not first_snapshot_processed:
                unique_y_set = set(row[y_index] for row in initial_snapshot_data)
                unique_z_set = set(row[z_index] for row in initial_snapshot_data)
                y_coords = sorted(list(unique_y_set))
                z_coords = sorted(list(unique_z_set))
                coord_to_index_map = {(y, z): (y_coords.index(y), z_coords.index(z)) for y in y_coords for z in z_coords}
                first_snapshot_processed = True

            if first_snapshot_processed:
                snapshot_array = _process_snapshot_data_with_fixed_coords(
                    current_snapshot_data, headers, y_index, z_index, dtype, y_coords, z_coords, coord_to_index_map
                )
                time_series_data.append(snapshot_array)

    if not time_series_data:
        return np.empty((0, 0, 0, 0), dtype=dtype), {}, headers

    first_shape = time_series_data[0].shape
    for i, snapshot in enumerate(time_series_data):
        if snapshot.shape != first_shape:
            raise ValueError(f"Snapshot at time index {i} has inconsistent shape {snapshot.shape} compared to the first snapshot {first_shape}.")

    stacked_array = np.stack(time_series_data)
    print(f"Data parsed from path: {file_path.resolve(strict=True)}")

    return stacked_array, coord_to_index_map, [h for h in headers if h not in ["y", "z"]]


In [10]:
data = {}
for suffix, path in zip(suffixes, paths):
    data[suffix] = {}
    data[suffix]['timeseries'], data[suffix]['labels'] = parse_tecplot_slice_to_numpy_timeseries(path)
    if print_loaded_data_example_ is True:
        print_loaded_data_example(data[suffix])
        print()

Data parsed from path: C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\sliceYZ_x0015_fld.dat
The data looks as follows:
N (number of snapshots) = 20000
n_y (grid height) = 49, n_z (grid width) = 49, n_v (number of variables) = 10
Labels:
['y', 'z', 'vx', 'vy', 'vz', 'jx', 'jy', 'jz', 'P', 'F']
Preview of the first snapshot:
[[-1.        -1.         0.       ]
 [-0.9882464 -1.         0.       ]
 [-0.9697327 -1.         0.       ]
 [-0.9446967 -1.         0.       ]
 [-0.9135254 -1.         0.       ]]

Data parsed from path: C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\sliceYZ_x0015_gradF.dat
The data looks as follows:
N (number of snapshots) = 20000
n_y (grid height) = 49, n_z (grid width) = 49, n_v (number of variables) = 5
Labels:
['y', 'z', 'dfdx', 'dfdy', 'dfdz']
Preview of the first snapshot:
[[-1.        -1.         0.2709205]
 [-0.9882464 -1.         0.2637546]
 [-0.9697327 -1.   

### Store

In [11]:
pickle_dir = Path("pkl")
pickle_paths = [slice_folder_path / pickle_dir / Path(f"sliceYZ_x0015_{suffix}.pkl") for suffix in suffixes]

In [12]:
for suffix, pickle_path in zip(suffixes, pickle_paths):
    save_object(data[suffix], pickle_path)

Object successfully saved to C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_fld.pkl
Object successfully saved to C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_gradF.pkl
Object successfully saved to C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_gradP.pkl
Object successfully saved to C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_gradU.pkl
Object successfully saved to C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_gradV.pkl
Object successfully saved to C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_gradW.pkl


### Verification

In [13]:
for suffix, pickle_path in zip(suffixes, pickle_paths):
    loaded_data = load_object(pickle_path)
    print_loaded_data_example(loaded_data)
    print()

Object successfully loaded from C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_fld.pkl
The data looks as follows:
N (number of snapshots) = 20000
n_y (grid height) = 49, n_z (grid width) = 49, n_v (number of variables) = 10
Labels:
['y', 'z', 'vx', 'vy', 'vz', 'jx', 'jy', 'jz', 'P', 'F']
Preview of the first snapshot:
[[-1.        -1.         0.       ]
 [-0.9882464 -1.         0.       ]
 [-0.9697327 -1.         0.       ]
 [-0.9446967 -1.         0.       ]
 [-0.9135254 -1.         0.       ]]

Object successfully loaded from C:\Users\hydro\Documents\PhD\nuclear_fusion_cooling\data\4pi_re1000_ha1000.384.pi\SliceYZ_x0015\pkl\sliceYZ_x0015_gradF.pkl
The data looks as follows:
N (number of snapshots) = 20000
n_y (grid height) = 49, n_z (grid width) = 49, n_v (number of variables) = 5
Labels:
['y', 'z', 'dfdx', 'dfdy', 'dfdz']
Preview of the first snapshot:
[[-1.        -1.         0.2709205]
 [-0.9882464 -1.         0.26

### Delete

In [14]:
if delete_files is True:
    for path in paths:
        abs_path = path.resolve()
        path.unlink()
        print(f"Successfully removed {abs_path}")